[package]
name = "lava-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
bip39 = "2.1.0"
bitcoin = "0.32.5"
esplora-client = { version = "0.11.0", features = ["blocking-https"] }
rand = "0.9.0"
regex = "1.11.1"
serde = "1.0.218"
serde_json = "1.0.140"
solana-sdk = "2.2.1"
